# SPDX-License-Identifier: Apache-2.0
---
# This task attempts dry run to check SAPCAR file in order to validate provided credentials.

- name: Validate Credentials - Dry run check user credentials and download privilege with Python venv
  when: sap_software_download_use_venv | d(true)
  community.sap_launchpad.software_center_download:
    suser_id: "{{ sap_software_download_suser_id }}"
    suser_password: "{{ sap_software_download_suser_password }}"
    search_query: "SAPCAR"
    download_path: "{{ sap_software_download_directory }}"
    search_alternatives: true
    deduplicate: "last"
    dry_run: true
  register: __sap_software_download_validate_credentials_venv
  retries: 1
  delay: 5
  environment:
    PATH: "{{ __sap_software_download_venv.path }}/bin:{{ ansible_env.PATH }}"
    PYTHONPATH: "{{ __sap_software_download_venv.path }}/lib/{{ sap_software_download_python_interpreter }}/site-packages"
    VIRTUAL_ENV: "{{ __sap_software_download_venv.path }}"
  vars:
    ansible_python_interpreter: "{{ __sap_software_download_venv.path ~ '/bin/' ~ sap_software_download_python_interpreter }}"
  ignore_errors: true  # Errors are ignored and validated afterwards

- name: Validate Credentials - Dry run check user credentials and download privilege with Python system default
  when: not sap_software_download_use_venv | d(true)
  community.sap_launchpad.software_center_download:
    suser_id: "{{ sap_software_download_suser_id }}"
    suser_password: "{{ sap_software_download_suser_password }}"
    search_query: "SAPCAR"
    download_path: "{{ sap_software_download_directory }}"
    search_alternatives: true
    deduplicate: "last"
    dry_run: true
  register: __sap_software_download_validate_credentials_default
  retries: 1
  delay: 5
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/' ~ sap_software_download_python_interpreter }}"
  ignore_errors: true  # Errors are ignored and validated afterwards

- name: Validate Credentials - Show failed results
  ansible.builtin.fail:
    msg: |
      Validation of provided S-User credentials failed.
      Ensure correct S-User credentials are provided in:
      `sap_software_download_suser_id` and `sap_software_download_suser_password`
  when:
    - (sap_software_download_use_venv | d(true)
        and __sap_software_download_validate_credentials_venv.failed is defined and __sap_software_download_validate_credentials_venv.failed)
      or (not sap_software_download_use_venv | d(true)
        and __sap_software_download_validate_credentials_default is defined and __sap_software_download_validate_credentials_default.failed)
